# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyMovieLeague' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyMovieLeague

  pod 'ObjectMapper'
  pod 'Alamofire', '~> 5.0'
  pod 'RealmSwift'
  pod 'UITextView+Placeholder'
  pod 'IQKeyboardManager'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'GaugeMeterView'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'GoogleSignIn'
  pod 'GradientProgressBar'
  pod 'SimpleImageViewer'
  pod 'PayUmoney_PnP'
  pod 'SDWebImage'
end
